[real_ip]
x_forwarded_for = 1
ipv4_prefix = 32
ipv6_prefix = 48

[botdetection.ip_limit]
# API access for n8n - allow more requests
request_max = 100
request_burst = 20
interval = 60
link_token = false

[botdetection.ip_lists]
pass_ip = [
  '127.0.0.1',
  '::1',
]